apiVersion: apps/v1
kind: Deployment
metadata:
  name: alphabet
  labels:
    app: alphabet
spec:
  replicas: 1
  selector:
    matchLabels:
      app: alphabet
  template:
    metadata:
      labels:
        app: alphabet
    spec:
      containers:
      - name: alphabet
        image: bentangled/alphabet-api/alphabet:latest
        imagePullPolicy: Never

---
apiVersion: v1
kind: Service
metadata:
  name: alphabet
spec:
  selector:
    app: alphabet
  ports:
    - name: alphabet
      protocol: TCP
      port: 80
      targetPort: 8080